"""
flood_detection_service.py
==========================
Sentinel-1 SAR Prototype Flood Detection Service.

PURPOSE
-------
Executes a simple, transparent low-backscatter thresholding method on
preprocessed Sentinel-1 SAR GeoTIFFs (generated by sar_preprocessing_service.py).

Produces a binary candidate mask:
- 0: Non-candidate land/surface
- 1: Potential flood / low-backscatter candidate
- -9999: NoData (border/invalid SAR pixels)

SCIENTIFIC HONESTY & KNOWN LIMITATIONS
--------------------------------------
This is a PROTOTYPE low-backscatter detection method for experimental / demonstration
purposes. It is NOT scientifically validated operational flood mapping.
- No radiometric calibration (sigma0 lookup) applied
- No terrain / DEM orthorectification applied
- No speckle filtering applied
- Water-lookalikes (smooth airport runways, calm water bodies, shadow zones) may produce low backscatter
- The output is strictly labeled: "Potential Flood / Low-Backscatter Candidate Mask"
"""

import json
import logging
import math
import os
import re
from typing import Any

import numpy as np
import rasterio

logger = logging.getLogger(__name__)

# Base local storage directory for Sentinel-1 products
_SENTINEL1_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", "data", "sentinel1")
)

# Directory containing preprocessed SAR rasters
_PROCESSED_DIR = os.path.join(_SENTINEL1_DIR, "processed")

# Output directory for prototype flood detection masks
_FLOOD_DIR = os.path.join(_SENTINEL1_DIR, "flood_detection")

# Allowed polarizations
ALLOWED_POLARIZATIONS = ("VV", "VH")

# Documented prototype default thresholds for Digital Number (DN) backscatter
DEFAULT_THRESHOLDS: dict[str, float] = {
    "VV": 150.0,
    "VH": 75.0,
}

# Default NoData value for flood mask GeoTIFF
FLOOD_NODATA = -9999

# Standard documented scientific limitations
DOCUMENTED_LIMITATIONS = [
    "Prototype threshold-based detection",
    "No radiometric calibration",
    "No terrain correction",
    "No speckle filtering",
    "Candidate mask is not scientifically validated flood classification",
]


def _get_safe_product_id(product_id: str) -> str:
    """Sanitize product ID to prevent directory traversal."""
    return re.sub(r"[^A-Za-z0-9_\-\.]", "_", (product_id or "").strip())


def get_raw_product_dir(product_id: str) -> str:
    """Return local directory for downloaded product."""
    safe_id = _get_safe_product_id(product_id)
    return os.path.join(_SENTINEL1_DIR, safe_id)


def get_processed_product_dir(product_id: str) -> str:
    """Return directory for preprocessed rasters."""
    safe_id = _get_safe_product_id(product_id)
    return os.path.join(_PROCESSED_DIR, safe_id)


def get_flood_product_dir(product_id: str) -> str:
    """Return output directory for flood detection products."""
    safe_id = _get_safe_product_id(product_id)
    return os.path.join(_FLOOD_DIR, safe_id)


def calculate_raster_area_m2(
    pixel_mask: np.ndarray,
    transform: rasterio.Affine,
    crs: Any,
    bounds: list[float],
) -> float:
    """
    Calculate real geospatial area in square meters for active mask pixels.

    Methodology:
    - If CRS is projected (linear unit = meters): uses pixel resolution dx * dy.
    - If CRS is geographic (e.g. EPSG:4326 degrees): uses WGS-84 ellipsoidal
      distance formulas per latitude row to calculate geodesic pixel area
      without treating degrees as meters.
    """
    height, width = pixel_mask.shape
    pixel_dx = abs(transform.a)
    pixel_dy = abs(transform.e)

    is_geographic = True
    if crs is not None:
        try:
            is_geographic = crs.is_geographic
        except Exception:
            is_geographic = True

    if not is_geographic:
        # Projected CRS: transform dimensions are directly in linear meters
        pixel_area_m2 = pixel_dx * pixel_dy
        pixel_count = int(np.count_nonzero(pixel_mask))
        return float(pixel_count * pixel_area_m2)

    # Geographic CRS (degrees): calculate per-row ellipsoidal geodesic area
    total_area_m2 = 0.0

    for r in range(height):
        row_active = int(np.count_nonzero(pixel_mask[r, :]))
        if row_active == 0:
            continue

        # Latitude of row center in degrees: transform.f is top (y origin), transform.e is dy (negative)
        row_lat_deg = transform.f + (r + 0.5) * transform.e
        lat_rad = math.radians(row_lat_deg)

        # WGS-84 ellipsoidal distance approximations per degree of lat/lon
        m_per_deg_lat = 111132.954 - 559.822 * math.cos(2.0 * lat_rad) + 1.175 * math.cos(4.0 * lat_rad)
        m_per_deg_lon = 111412.84 * math.cos(lat_rad) - 93.5 * math.cos(3.0 * lat_rad)

        pixel_w_m = pixel_dx * m_per_deg_lon
        pixel_h_m = pixel_dy * m_per_deg_lat
        row_pixel_area_m2 = pixel_w_m * pixel_h_m

        total_area_m2 += row_active * row_pixel_area_m2

    return float(total_area_m2)


def detect_sentinel1_flood(
    product_id: str,
    polarization: str = "VV",
    threshold: float | None = None,
    force: bool = False,
) -> dict[str, Any]:
    """
    Execute Prototype SAR Flood Detection for a preprocessed Sentinel-1 raster.

    Parameters
    ----------
    product_id : str
        Sentinel-1 product ID.
    polarization : str
        Polarization to analyze ('VV' or 'VH').
    threshold : float | None
        Low-backscatter DN threshold. If None, uses documented prototype default.
    force : bool
        If True, re-processes even if output already exists.

    Returns
    -------
    dict with detection metrics, output paths, and limitations.
    """
    safe_id = _get_safe_product_id(product_id)
    if not safe_id:
        return {
            "status": "error",
            "message": "Invalid or empty product_id provided.",
        }

    pol = (polarization or "").strip().upper()
    if pol not in ALLOWED_POLARIZATIONS:
        return {
            "status": "invalid_polarization",
            "message": f"Invalid polarization '{polarization}'. Supported polarizations are 'VV' and 'VH'.",
        }

    # Validate threshold
    if threshold is not None:
        try:
            threshold_val = float(threshold)
            if threshold_val <= 0:
                return {
                    "status": "invalid_threshold",
                    "message": f"Threshold must be a positive number. Received: {threshold}",
                }
        except (ValueError, TypeError):
            return {
                "status": "invalid_threshold",
                "message": f"Threshold must be a valid numeric value. Received: {threshold}",
            }
    else:
        threshold_val = DEFAULT_THRESHOLDS.get(pol, 150.0)

    # 1. Verify raw product directory exists locally
    raw_dir = get_raw_product_dir(safe_id)
    if not os.path.isdir(raw_dir):
        return {
            "status": "not_found",
            "message": f"Sentinel-1 product '{safe_id}' was not found in downloaded storage.",
        }

    # 2. Verify SAR preprocessing has been completed
    processed_dir = get_processed_product_dir(safe_id)
    if not os.path.isdir(processed_dir):
        return {
            "status": "not_preprocessed",
            "message": (
                f"SAR preprocessing has not been completed for product '{safe_id}'. "
                "Execute SAR preprocessing first before running flood detection."
            ),
        }

    # Locate preprocessed GeoTIFF
    input_filename = f"{pol.lower()}_processed.tif"
    input_raster_path = os.path.join(processed_dir, input_filename)

    if not os.path.isfile(input_raster_path):
        return {
            "status": "not_preprocessed",
            "message": (
                f"Preprocessed {pol} GeoTIFF '{input_filename}' not found for product '{safe_id}'. "
                f"Preprocess polarization {pol} before running flood detection."
            ),
        }

    # 3. Check for existing duplicate detection
    flood_dir = get_flood_product_dir(safe_id)
    output_filename = f"flood_mask_{pol.lower()}.tif"
    final_mask_path = os.path.join(flood_dir, output_filename)
    meta_json_path = os.path.join(flood_dir, "metadata.json")

    if not force and os.path.isfile(final_mask_path) and os.path.isfile(meta_json_path):
        try:
            with open(meta_json_path, "r", encoding="utf-8") as f:
                all_meta = json.load(f)
            if pol in all_meta:
                existing_res = all_meta[pol]
                # Return ALREADY_EXISTS with preserved metadata
                return {
                    **existing_res,
                    "status": "already_processed",
                    "processing_status": "ALREADY_EXISTS",
                }
        except Exception as e:
            logger.warning("Could not read existing flood detection metadata: %s", e)

    # 4. Read the preprocessed SAR raster with Rasterio
    try:
        with rasterio.open(input_raster_path) as src:
            data = src.read(1)
            src_meta = src.meta.copy()
            src_nodata = src.nodata
            crs = src.crs
            transform = src.transform
            width = src.width
            height = src.height
            bounds = [float(b) for b in src.bounds]
            crs_str = str(crs) if crs else "EPSG:4326"
    except Exception as e:
        logger.error("Failed to read preprocessed SAR raster '%s': %s", input_raster_path, e)
        return {
            "status": "error",
            "message": f"Failed to read preprocessed SAR raster: {str(e)}",
        }

    if width <= 0 or height <= 0:
        return {
            "status": "error",
            "message": f"Invalid raster dimensions: width={width}, height={height}",
        }

    # 5. Mask invalid / NoData pixels
    if src_nodata is not None and not np.isnan(src_nodata):
        valid_mask = (data != src_nodata) & ~np.isnan(data) & ~np.isinf(data)
    else:
        valid_mask = ~np.isnan(data) & ~np.isinf(data)

    valid_pixel_count = int(np.count_nonzero(valid_mask))
    total_pixels = int(width * height)

    if valid_pixel_count == 0:
        return {
            "status": "error",
            "message": f"Preprocessed raster contains 0 valid pixels.",
        }

    # 6. Apply transparent low-backscatter threshold method
    # Rule: valid SAR pixel AND backscatter DN <= threshold → potential flood/water candidate
    candidate_flood_mask = valid_mask & (data <= threshold_val)
    candidate_flood_pixels = int(np.count_nonzero(candidate_flood_mask))

    flood_percentage = round((candidate_flood_pixels / valid_pixel_count) * 100.0, 2)

    # 7. Calculate real geospatial area
    detected_area_m2 = calculate_raster_area_m2(candidate_flood_mask, transform, crs, bounds)
    total_analyzed_area_m2 = calculate_raster_area_m2(valid_mask, transform, crs, bounds)

    detected_area_km2 = round(detected_area_m2 / 1_000_000.0, 4)
    total_analyzed_area_km2 = round(total_analyzed_area_m2 / 1_000_000.0, 4)

    # 8. Create binary flood mask array
    # 0 = non-candidate, 1 = potential flood/water candidate, -9999 = NoData
    mask_array = np.full((height, width), FLOOD_NODATA, dtype=np.int16)
    mask_array[valid_mask] = 0
    mask_array[candidate_flood_mask] = 1

    # 9. Atomic GeoTIFF writing
    os.makedirs(flood_dir, exist_ok=True)
    tmp_mask_path = os.path.join(flood_dir, f".{output_filename}.tmp.{os.getpid()}")

    out_profile = src_meta.copy()
    out_profile.update(
        dtype=rasterio.int16,
        count=1,
        nodata=FLOOD_NODATA,
        compress="deflate",
    )

    try:
        with rasterio.open(tmp_mask_path, "w", **out_profile) as dst:
            dst.write(mask_array, 1)

        # Atomic replace
        os.replace(tmp_mask_path, final_mask_path)
    except Exception as e:
        if os.path.exists(tmp_mask_path):
            try:
                os.remove(tmp_mask_path)
            except OSError:
                pass
        logger.error("Failed to write flood mask GeoTIFF: %s", e)
        return {
            "status": "error",
            "message": f"Failed to write flood mask GeoTIFF: {str(e)}",
        }

    # Verify written mask can be opened with Rasterio
    try:
        with rasterio.open(final_mask_path) as check_src:
            assert check_src.width == width
            assert check_src.height == height
            assert check_src.nodata == FLOOD_NODATA
    except Exception as e:
        logger.error("Integrity check failed for generated mask '%s': %s", final_mask_path, e)
        return {
            "status": "error",
            "message": f"Generated mask integrity check failed: {str(e)}",
        }

    # 10. Write detection metadata
    rel_output_file = f"sentinel1/flood_detection/{safe_id}/{output_filename}"

    result_data = {
        "status": "success",
        "product_id": safe_id,
        "polarization": pol,
        "threshold_used": float(threshold_val),
        "processing_method": "Prototype SAR Flood Detection",
        "classification": "Potential Flood / Low-Backscatter Candidate Mask",
        "processing_status": "COMPLETED",
        "output_file": rel_output_file,
        "width": width,
        "height": height,
        "crs": crs_str,
        "bounds": bounds,
        "valid_pixels": valid_pixel_count,
        "valid_pixel_count": valid_pixel_count,
        "total_pixels": total_pixels,
        "candidate_flood_pixels": candidate_flood_pixels,
        "flood_pixel_count": candidate_flood_pixels,
        "flood_percentage": flood_percentage,
        "detected_area_m2": round(detected_area_m2, 2),
        "detected_area_km2": detected_area_km2,
        "analyzed_area_m2": round(total_analyzed_area_m2, 2),
        "analyzed_area_km2": total_analyzed_area_km2,
        "nodata": FLOOD_NODATA,
        "method": "Prototype SAR Flood Detection (Low-Backscatter Thresholding)",
        "area_calculation_method": (
            "WGS-84 Ellipsoidal Geodesic Pixel Area" if (crs and crs.is_geographic) else "Planar Linear Pixel Area"
        ),
        "limitations": DOCUMENTED_LIMITATIONS,
    }

    # Update metadata.json atomically
    existing_all_meta = {}
    if os.path.isfile(meta_json_path):
        try:
            with open(meta_json_path, "r", encoding="utf-8") as f:
                existing_all_meta = json.load(f)
        except Exception:
            existing_all_meta = {}

    existing_all_meta[pol] = result_data

    tmp_meta_path = os.path.join(flood_dir, f".metadata.json.tmp.{os.getpid()}")
    try:
        with open(tmp_meta_path, "w", encoding="utf-8") as f:
            json.dump(existing_all_meta, f, indent=2)
        os.replace(tmp_meta_path, meta_json_path)
    except Exception as e:
        if os.path.exists(tmp_meta_path):
            try:
                os.remove(tmp_meta_path)
            except OSError:
                pass
        logger.warning("Could not persist flood detection metadata.json: %s", e)

    return result_data


def get_flood_detection_status(
    product_id: str,
    polarization: str | None = None,
) -> dict[str, Any]:
    """
    Check the current flood detection status for a Sentinel-1 product.

    Parameters
    ----------
    product_id : str
        Sentinel-1 product ID.
    polarization : str | None
        Optional specific polarization to query ('VV' or 'VH').

    Returns
    -------
    dict with detection status and metadata.
    """
    safe_id = _get_safe_product_id(product_id)
    if not safe_id:
        return {
            "status": "error",
            "message": "Invalid product ID.",
        }

    pol = polarization.strip().upper() if polarization else None
    if pol is not None and pol not in ALLOWED_POLARIZATIONS:
        return {
            "status": "invalid_polarization",
            "message": f"Invalid polarization '{polarization}'. Supported: 'VV', 'VH'.",
        }

    flood_dir = get_flood_product_dir(safe_id)
    meta_json_path = os.path.join(flood_dir, "metadata.json")

    detected_polarizations: list[str] = []
    detected_metadata: dict[str, Any] = {}

    if os.path.isdir(flood_dir) and os.path.isfile(meta_json_path):
        try:
            with open(meta_json_path, "r", encoding="utf-8") as f:
                all_meta = json.load(f)
            for p in ALLOWED_POLARIZATIONS:
                mask_file = os.path.join(flood_dir, f"flood_mask_{p.lower()}.tif")
                if p in all_meta and os.path.isfile(mask_file):
                    detected_polarizations.append(p)
                    detected_metadata[p] = all_meta[p]
        except Exception as e:
            logger.warning("Error reading flood detection status for '%s': %s", safe_id, e)

    if pol:
        # Status for specific polarization
        if pol in detected_polarizations:
            return {
                "product_id": safe_id,
                "polarization": pol,
                "status": "COMPLETED",
                "processing_status": "COMPLETED",
                "metadata": detected_metadata.get(pol),
            }
        else:
            return {
                "product_id": safe_id,
                "polarization": pol,
                "status": "NOT_PROCESSED",
                "processing_status": "NOT_PROCESSED",
            }

    if len(detected_polarizations) == len(ALLOWED_POLARIZATIONS):
        overall_status = "COMPLETED"
    elif len(detected_polarizations) > 0:
        overall_status = "PARTIAL"
    else:
        overall_status = "NOT_PROCESSED"

    return {
        "product_id": safe_id,
        "status": overall_status,
        "detected_polarizations": detected_polarizations,
        "detected_metadata": detected_metadata,
    }

